---
title: "S18805_ST405_Mini_Project_2"
author: "S/18/805"
date: "2024-05-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(skimr)
library(CCA)
library(CCP)
library(candisc)
```

```{r}
data <-read_csv("../Data/led.csv")
data %>% view()
```

```{r}
skim(data)
```

```{r}
clean_data <- na.omit(data) 
view(clean_data)
```

```{r}
skim(clean_data)
```

```{r}
clean_data <- clean_data[,-c(1,2,3)] 
```

```{r}
head(clean_data)
```


```{r}
std_data <- apply(clean_data,2,scale)
```

```{r}
head(std_data)
```

```{r}
mortal_var <-std_data[,c("Lifeexpectancy","AdultMortality","infantdeaths","under-fivedeaths","HIV/AIDS")]

health_var <- std_data[,c("Alcohol","HepatitisB","Measles","BMI","Polio","Totalexpenditure","Diphtheria",
                      "thinness1-19years","thinness5-9years")]
```

```{r}
ccv <- cc(mortal_var,health_var)
#ccv
```

```{r}
ccv$cor
```

```{r}
cancor(mortal_var,health_var)
```

```{r}
Wilks(mortal_var,health_var,ccv)
```





















